FROM golang:1.15 as build

RUN apt-get update && apt-get install -y ninja-build

RUN go get -u github.com/AlmostGreatBand/KPI2-1/build/cmd/bood

WORKDIR /go/src/practice-2
COPY . .

ENTRYPOINT ["bood", "out/test/integration_tests"]
